-- This file is auto-generated by install.sh with actual passwords.
-- If you see this placeholder, run the installer again.
-- The generate_nuxbill_sql() function in install.sh creates the real version.
CREATE DATABASE IF NOT EXISTS phpnuxbill CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
-- User creation requires the actual password from .env
