#!/bin/bash
set -Eeuo pipefail

# ══════════════════════════════════════════════
#  PHPNuxBill Entrypoint — OmniSync Stack
# ══════════════════════════════════════════════

NUXROOT="/var/www/html"
CONFIG_FILE="$NUXROOT/config.php"

DB_HOST="${NUXBILL_DB_HOST:-mariadb}"
DB_USER="${NUXBILL_DB_USER:-nuxbill}"
DB_PASS="${NUXBILL_DB_PASS:-${NUXBILL_DB_PASSWORD:-changeme_nuxbill}}"
DB_NAME="${NUXBILL_DB_NAME:-phpnuxbill}"
APP_URL="${NUXBILL_APP_URL:-http://localhost:8080}"
TZ_VALUE="${TZ:-America/Bogota}"

RADIUS_DB_HOST="${RADIUS_DB_HOST:-$DB_HOST}"
RADIUS_DB_PORT="${RADIUS_DB_PORT:-3306}"
RADIUS_DB_USER="${RADIUS_DB_USER:-radius}"
RADIUS_DB_PASS="${RADIUS_DB_PASS:-changeme_radius}"
RADIUS_DB_NAME="${RADIUS_DB_NAME:-radius}"

log() { echo "[nuxbill] $1"; }

# ── 1) Generate config.php ──────────────────────
generate_config() {
  local app_key
  app_key=$(echo -n "${DB_PASS}${DB_HOST}" | md5sum | cut -d' ' -f1)

  cat > "$CONFIG_FILE" <<PHP
<?php
// Auto-generated by OmniSync
\$db_host     = '${DB_HOST}';
\$db_user     = '${DB_USER}';
\$db_pass     = '${DB_PASS}';
\$db_password = '${DB_PASS}';
\$db_name     = '${DB_NAME}';

\$radius_host     = '${RADIUS_DB_HOST}';
\$radius_port     = '${RADIUS_DB_PORT}';
\$radius_user     = '${RADIUS_DB_USER}';
\$radius_pass     = '${RADIUS_DB_PASS}';
\$radius_password = '${RADIUS_DB_PASS}';
\$radius_name     = '${RADIUS_DB_NAME}';

define('APP_URL', '${APP_URL}');
\$APP_URL = APP_URL;

\$_app_stage = 'Live';
\$app_stage  = \$_app_stage;

\$APP_KEY = '${app_key}';

date_default_timezone_set('${TZ_VALUE}');
PHP

  chown www-data:www-data "$CONFIG_FILE"
  chmod 644 "$CONFIG_FILE"
  log "config.php generado ✓"
}

# ── 2) Wait for MariaDB ─────────────────────────
wait_mariadb() {
  log "Esperando MariaDB ($DB_HOST)..."
  for i in $(seq 1 40); do
    if php -r "
      \$c = @new mysqli('${DB_HOST}', '${DB_USER}', '${DB_PASS}', '${DB_NAME}');
      exit(\$c->connect_error ? 1 : 0);
    " 2>/dev/null; then
      log "MariaDB conectada ✓"
      return 0
    fi
    sleep 2
  done
  log "⚠ No se pudo conectar a MariaDB después de 80s"
  return 1
}

# ── 3) Import schema if needed ───────────────────
import_schema() {
  local has_tables
  has_tables=$(php -r "
    \$c = new mysqli('${DB_HOST}', '${DB_USER}', '${DB_PASS}', '${DB_NAME}');
    if (\$c->connect_error) { echo '0'; exit; }
    \$r = \$c->query(\"SHOW TABLES LIKE 'tbl_appconfig'\");
    echo (\$r && \$r->num_rows > 0) ? '1' : '0';
    \$c->close();
  " 2>/dev/null || echo "0")

  if [ "$has_tables" = "1" ]; then
    log "Schema PHPNuxBill ya existe ✓"
    return 0
  fi

  log "Importando schema PHPNuxBill..."
  local sql_file=""
  for candidate in \
    "$NUXROOT/install/phpnuxbill.sql" \
    "$NUXROOT/install/sql/phpnuxbill.sql" \
    "$NUXROOT/system/uploads/phpnuxbill.sql" \
    "$NUXROOT/install/database.sql"; do
    if [ -f "$candidate" ]; then
      sql_file="$candidate"
      break
    fi
  done

  # Fallback: find any .sql in install/
  if [ -z "$sql_file" ]; then
    sql_file=$(find "$NUXROOT" -name "phpnuxbill.sql" -type f 2>/dev/null | head -1)
  fi

  if [ -z "$sql_file" ] || [ ! -f "$sql_file" ]; then
    log "⚠ No se encontró schema SQL — use el instalador web"
    return 1
  fi

  php -r "
    \$c = new mysqli('${DB_HOST}', '${DB_USER}', '${DB_PASS}', '${DB_NAME}');
    if (\$c->connect_error) { exit(1); }
    \$sql = file_get_contents('${sql_file}');
    if (!\$c->multi_query(\$sql)) { exit(1); }
    while (\$c->more_results() && \$c->next_result()) {
      if (\$r = \$c->store_result()) \$r->free();
    }
    \$c->close();
  " 2>/dev/null && log "Schema importado ✓" || { log "⚠ Error importando schema"; return 1; }
}

# ── 4) Import RADIUS schema ─────────────────────
import_radius_schema() {
  local schema_file="/docker-entrypoint-initdb.d/radius-schema.sql"
  [ -f "$schema_file" ] || return 0

  local has_nas
  has_nas=$(php -r "
    \$c = @new mysqli('${RADIUS_DB_HOST}', '${RADIUS_DB_USER}', '${RADIUS_DB_PASS}', '${RADIUS_DB_NAME}');
    if (\$c->connect_error) { echo '0'; exit; }
    \$r = \$c->query(\"SHOW TABLES LIKE 'nas'\");
    echo (\$r && \$r->num_rows > 0) ? '1' : '0';
    \$c->close();
  " 2>/dev/null || echo "0")

  if [ "$has_nas" = "1" ]; then
    log "Tablas RADIUS existen ✓"
    return 0
  fi

  log "Importando schema RADIUS..."
  if command -v mysql >/dev/null 2>&1; then
    mysql -h"$RADIUS_DB_HOST" -u"$RADIUS_DB_USER" -p"$RADIUS_DB_PASS" "$RADIUS_DB_NAME" < "$schema_file" 2>/dev/null \
      && log "Schema RADIUS importado (mysql client) ✓" && return 0
  fi

  php -r "
    \$c = new mysqli('${RADIUS_DB_HOST}', '${RADIUS_DB_USER}', '${RADIUS_DB_PASS}', '${RADIUS_DB_NAME}');
    if (\$c->connect_error) { exit(1); }
    \$sql = file_get_contents('${schema_file}');
    \$c->multi_query(\$sql);
    do { if (\$r = \$c->store_result()) \$r->free(); } while (\$c->more_results() && \$c->next_result());
    \$c->close();
  " 2>/dev/null && log "Schema RADIUS importado (PHP) ✓" || log "⚠ Error importando schema RADIUS"
}

# ── 5) Create admin + configure app ─────────────
setup_admin() {
  php -r "
    \$c = new mysqli('${DB_HOST}', '${DB_USER}', '${DB_PASS}', '${DB_NAME}');
    if (\$c->connect_error) exit;

    // Admin user
    \$r = \$c->query(\"SELECT id FROM tbl_users WHERE username='admin'\");
    if (\$r && \$r->num_rows == 0) {
      \$h = sha1('admin');
      \$c->query(\"INSERT INTO tbl_users (username,password,fullname,user_type,status) VALUES ('admin','\$h','Administrator','Admin','Active')\");
      echo 'Admin creado (admin/admin) ✓' . PHP_EOL;
    }

    // Force Live mode + RADIUS config
    \$settings = [
      'app_stage'       => 'Live',
      'radius_enable'   => '1',
      'radius_host'     => '${RADIUS_DB_HOST}',
      'radius_user'     => '${RADIUS_DB_USER}',
      'radius_pass'     => '${RADIUS_DB_PASS}',
      'radius_name'     => '${RADIUS_DB_NAME}',
      'radius_db_host'  => '${RADIUS_DB_HOST}',
      'radius_db_user'  => '${RADIUS_DB_USER}',
      'radius_db_pass'  => '${RADIUS_DB_PASS}',
      'radius_db_name'  => '${RADIUS_DB_NAME}',
    ];
    foreach (\$settings as \$k => \$v) {
      \$ks = \$c->real_escape_string(\$k);
      \$vs = \$c->real_escape_string(\$v);
      \$c->query(\"INSERT INTO tbl_appconfig (setting,value) VALUES ('\$ks','\$vs') ON DUPLICATE KEY UPDATE value='\$vs'\");
    }

    \$c->close();
    echo 'Config aplicada ✓' . PHP_EOL;
  " 2>/dev/null || true

  # Remove install dir to skip installer
  if [ -d "$NUXROOT/install" ]; then
    mv "$NUXROOT/install" "$NUXROOT/install.bak" 2>/dev/null || true
    log "install/ → install.bak ✓"
  fi
}

# ── 6) Setup cron (bulletproof) ──────────────────
setup_cron() {
  local cron_url="http://127.0.0.1:8080/index.php?_route=cron/run"
  local ts_file="$NUXROOT/system/uploads/cron_last_run.txt"

  mkdir -p "$(dirname "$ts_file")"
  date +%s > "$ts_file"
  chown www-data:www-data "$ts_file" 2>/dev/null || true

  # Suppress cron warnings in DB
  php -r "
    \$c = @new mysqli('${DB_HOST}', '${DB_USER}', '${DB_PASS}', '${DB_NAME}');
    if (\$c->connect_error) exit;
    foreach (['cron_last_run'=>date('Y-m-d H:i:s'),'cron_period'=>'1','cron_status'=>'1',
              'cron_active'=>'1','disable_cron_warning'=>'1','cron_enabled'=>'1',
              'cron_enable'=>'1','cron_warning'=>'0'] as \$k=>\$v) {
      \$c->query(\"INSERT INTO tbl_appconfig (setting,value) VALUES ('\$k','\$v') ON DUPLICATE KEY UPDATE value='\$v'\");
    }
    \$c->close();
  " 2>/dev/null || true

  # System cron job
  cat > /etc/cron.d/phpnuxbill <<CRON
* * * * * root curl -sf '$cron_url' > /dev/null 2>&1 || /usr/local/bin/php $NUXROOT/system/cron.php > /dev/null 2>&1; date +\%s > '$ts_file'
0 7 * * * root cd $NUXROOT/system && /usr/local/bin/php cron_reminder.php > /dev/null 2>&1
CRON
  chmod 0644 /etc/cron.d/phpnuxbill

  # Start cron daemon
  if command -v cron >/dev/null 2>&1; then
    cron && log "Cron daemon iniciado ✓"
  elif command -v crond >/dev/null 2>&1; then
    crond && log "Cron daemon iniciado ✓"
  fi

  # Background heartbeat: keeps DB timestamp fresh every 60s
  (
    sleep 20
    while true; do
      curl -sf "$cron_url" > /dev/null 2>&1 \
        || /usr/local/bin/php "$NUXROOT/system/cron.php" > /dev/null 2>&1 \
        || true
      date +%s > "$ts_file" 2>/dev/null || true
      php -r "
        \$c = @new mysqli('${DB_HOST}', '${DB_USER}', '${DB_PASS}', '${DB_NAME}');
        if (!\$c->connect_error) {
          \$c->query(\"UPDATE tbl_appconfig SET value=NOW() WHERE setting='cron_last_run'\");
          \$c->query(\"UPDATE tbl_appconfig SET value='1' WHERE setting IN ('cron_active','cron_status','cron_enabled','cron_enable','disable_cron_warning')\");
          \$c->query(\"UPDATE tbl_appconfig SET value='0' WHERE setting='cron_warning'\");
          \$c->close();
        }
      " > /dev/null 2>&1 || true
      sleep 60
    done
  ) &

  log "Cron configurado ✓"
}

# ── 7) Fix permissions ───────────────────────────
fix_permissions() {
  chown -R www-data:www-data "$NUXROOT"
  chmod -R 755 "$NUXROOT"
  chmod -R 775 "$NUXROOT/system/uploads" "$NUXROOT/system/cache" "$NUXROOT/ui/cache" 2>/dev/null || true
  log "Permisos corregidos ✓"
}

# ══════════════════════════════════════════════════
#  MAIN
# ══════════════════════════════════════════════════
log "=== Iniciando PHPNuxBill ==="

generate_config

if wait_mariadb; then
  import_schema
  import_radius_schema
  setup_admin
  setup_cron
fi

fix_permissions

log "=== PHPNuxBill listo ==="
exec "$@"
