#!/bin/bash
set -e

echo "=== Configurando PHPNuxBill ==="

NUXROOT="/var/www/html"

# ── 1. Detect subdirectory installs ──
if [ ! -f "$NUXROOT/index.php" ] && [ -f "$NUXROOT/phpnuxbill/index.php" ]; then
  cp -r "$NUXROOT/phpnuxbill/"* "$NUXROOT/" 2>/dev/null || true
  cp -r "$NUXROOT/phpnuxbill/."* "$NUXROOT/" 2>/dev/null || true
  rm -rf "$NUXROOT/phpnuxbill"
  echo "Archivos movidos al webroot ✓"
fi

CONFIG_FILE="$NUXROOT/config.php"

APP_KEY=$(echo -n "${NUXBILL_DB_PASS}${NUXBILL_DB_HOST}" | md5sum | cut -d' ' -f1)

# ── 2. Generate config.php ──
if [ -n "$NUXBILL_DB_HOST" ]; then
  echo '<?php' > "$CONFIG_FILE"
  echo '// Auto-generated by OmniSync installer' >> "$CONFIG_FILE"
  echo "\$db_host = '${NUXBILL_DB_HOST}';" >> "$CONFIG_FILE"
  echo "\$db_user = '${NUXBILL_DB_USER}';" >> "$CONFIG_FILE"
  echo "\$db_pass = '${NUXBILL_DB_PASS}';" >> "$CONFIG_FILE"
  echo "\$db_password = '${NUXBILL_DB_PASS}';" >> "$CONFIG_FILE"
  echo "\$db_name = '${NUXBILL_DB_NAME}';" >> "$CONFIG_FILE"
  echo '' >> "$CONFIG_FILE"
  echo "define('APP_URL', '${NUXBILL_APP_URL:-http://localhost:8080}');" >> "$CONFIG_FILE"
  echo "\$APP_URL = APP_URL;" >> "$CONFIG_FILE"
  echo '' >> "$CONFIG_FILE"
  echo "\$_app_stage = 'Live';" >> "$CONFIG_FILE"
  echo "\$app_stage = \$_app_stage;" >> "$CONFIG_FILE"
  echo '' >> "$CONFIG_FILE"
  echo "\$APP_KEY = '${APP_KEY}';" >> "$CONFIG_FILE"
  echo '' >> "$CONFIG_FILE"
  echo "date_default_timezone_set('${TZ:-America/Bogota}');" >> "$CONFIG_FILE"

  chown www-data:www-data "$CONFIG_FILE"
  chmod 644 "$CONFIG_FILE"
  echo "PHPNuxBill config.php creado ✓"
fi

# ── 3. Wait for MariaDB ──
echo "Esperando MariaDB..."
CONNECTED=false
for i in $(seq 1 30); do
  if php -r "new mysqli('${NUXBILL_DB_HOST:-mariadb}', '${NUXBILL_DB_USER:-nuxbill}', '${NUXBILL_DB_PASS:-changeme}', '${NUXBILL_DB_NAME:-phpnuxbill}');" 2>/dev/null; then
    echo "MariaDB conectada ✓"
    CONNECTED=true
    break
  fi
  echo "Reintentando ($i/30)..."
  sleep 2
done

# ── 4. Auto-install schema ──
SCHEMA_FOUND=false
if [ "$CONNECTED" = true ]; then
  TABLE_CHECK=$(php -r "
    \$c = new mysqli('${NUXBILL_DB_HOST:-mariadb}', '${NUXBILL_DB_USER:-nuxbill}', '${NUXBILL_DB_PASS:-changeme}', '${NUXBILL_DB_NAME:-phpnuxbill}');
    \$r = \$c->query(\"SHOW TABLES LIKE 'tbl_appconfig'\");
    echo ((\$r && \$r->num_rows > 0) ? '1' : '0');
    \$c->close();
  " 2>/dev/null || echo "0")

  if [ "$TABLE_CHECK" = "0" ]; then
    echo "Tablas no encontradas, buscando schema..."

    # List all SQL files for debugging
    echo "Archivos SQL disponibles:"
    find "$NUXROOT" -name "*.sql" 2>/dev/null | head -20

    # Search in common locations
    for sql_file in \
      "$NUXROOT/install/phpnuxbill.sql" \
      "$NUXROOT/install/sql/phpnuxbill.sql" \
      "$NUXROOT/system/uploads/phpnuxbill.sql" \
      "$NUXROOT/install/database.sql" \
      "$NUXROOT/install/install.sql" \
      "$NUXROOT/sql/install.sql" \
      $(find "$NUXROOT" -name "phpnuxbill.sql" 2>/dev/null) \
      $(find "$NUXROOT/install" -name "*.sql" 2>/dev/null | head -3); do
      [ -z "$sql_file" ] && continue
      if [ -f "$sql_file" ]; then
        echo "Importando schema: $sql_file"
        php -r "
          \$c = new mysqli('${NUXBILL_DB_HOST:-mariadb}', '${NUXBILL_DB_USER:-nuxbill}', '${NUXBILL_DB_PASS:-changeme}', '${NUXBILL_DB_NAME:-phpnuxbill}');
          \$sql = file_get_contents('$sql_file');
          \$c->multi_query(\$sql);
          while (\$c->next_result()) {;}
          \$c->close();
          echo 'OK';
        " 2>/dev/null && SCHEMA_FOUND=true
        if [ "$SCHEMA_FOUND" = true ]; then
          break
        fi
      fi
    done

    if [ "$SCHEMA_FOUND" = true ]; then
      echo "Schema importado ✓"
    else
      echo "⚠ No se encontró schema SQL. Acceda vía navegador para instalar."
      # Don't delete install dir - let web installer work
      if [ -d "$NUXROOT/install" ]; then
        chown -R www-data:www-data "$NUXROOT/install"
        echo "Directorio install/ disponible para instalación web"
      fi
    fi
  else
    echo "PHPNuxBill schema ya existe ✓"
    SCHEMA_FOUND=true  
  fi
fi

# ── 5. Create admin user and set Live stage ──
if [ "$CONNECTED" = true ] && [ "$SCHEMA_FOUND" = true ]; then
  php -r "
    \$c = new mysqli('${NUXBILL_DB_HOST:-mariadb}', '${NUXBILL_DB_USER:-nuxbill}', '${NUXBILL_DB_PASS:-changeme}', '${NUXBILL_DB_NAME:-phpnuxbill}');
    if (\$c->connect_error) { echo 'DB error'; exit; }

    // Check if admin exists
    \$r = \$c->query(\"SELECT id FROM tbl_users WHERE username='admin'\");
    if (\$r && \$r->num_rows == 0) {
      // PHPNuxBill uses md5 for passwords
      \$hash = md5('admin');
      \$c->query(\"INSERT INTO tbl_users (username, password, fullname, user_type, status) VALUES ('admin', '\$hash', 'Administrator', 'Admin', 'Active')\");
      echo 'Admin creado (admin/admin) ✓';
    } else {
      echo 'Admin ya existe ✓';
    }

    // Force Live stage
    \$c->query(\"INSERT INTO tbl_appconfig (setting, value) VALUES ('app_stage', 'Live') ON DUPLICATE KEY UPDATE value='Live'\");

    \$c->close();
  " 2>/dev/null || true

  # Remove install directory to prevent redirect loop
  if [ -d "$NUXROOT/install" ]; then
    mv "$NUXROOT/install" "$NUXROOT/install.bak" 2>/dev/null || true
    echo "Directorio install/ renombrado a install.bak ✓"
  fi
fi

# ── 6. Permissions ──
chown -R www-data:www-data "$NUXROOT"
chmod -R 755 "$NUXROOT"

echo "=== PHPNuxBill listo ==="
exec "$@"
