#!/bin/bash
set -e

echo "=== Configurando PHPNuxBill ==="

NUXROOT="/var/www/html"

# ── 1. Detect subdirectory installs ──
if [ ! -f "$NUXROOT/index.php" ] && [ -f "$NUXROOT/phpnuxbill/index.php" ]; then
  cp -r "$NUXROOT/phpnuxbill/"* "$NUXROOT/" 2>/dev/null || true
  cp -r "$NUXROOT/phpnuxbill/."* "$NUXROOT/" 2>/dev/null || true
  rm -rf "$NUXROOT/phpnuxbill"
  echo "Archivos movidos al webroot ✓"
fi

CONFIG_FILE="$NUXROOT/config.php"

APP_KEY=$(echo -n "${NUXBILL_DB_PASS}${NUXBILL_DB_HOST}" | md5sum | cut -d' ' -f1)

# ── 2. Generate config.php ──
if [ -n "$NUXBILL_DB_HOST" ]; then
  echo '<?php' > "$CONFIG_FILE"
  echo '// Auto-generated by OmniSync installer' >> "$CONFIG_FILE"
  echo "\$db_host = '${NUXBILL_DB_HOST}';" >> "$CONFIG_FILE"
  echo "\$db_user = '${NUXBILL_DB_USER}';" >> "$CONFIG_FILE"
  echo "\$db_pass = '${NUXBILL_DB_PASS}';" >> "$CONFIG_FILE"
  echo "\$db_password = '${NUXBILL_DB_PASS}';" >> "$CONFIG_FILE"
  echo "\$db_name = '${NUXBILL_DB_NAME}';" >> "$CONFIG_FILE"
  echo '' >> "$CONFIG_FILE"
  echo "define('APP_URL', '${NUXBILL_APP_URL:-http://localhost:8080}');" >> "$CONFIG_FILE"
  echo "\$APP_URL = APP_URL;" >> "$CONFIG_FILE"
  echo '' >> "$CONFIG_FILE"
  echo "\$_app_stage = 'Live';" >> "$CONFIG_FILE"
  echo "\$app_stage = \$_app_stage;" >> "$CONFIG_FILE"
  echo '' >> "$CONFIG_FILE"
  echo "\$APP_KEY = '${APP_KEY}';" >> "$CONFIG_FILE"
  echo '' >> "$CONFIG_FILE"
  echo "date_default_timezone_set('${TZ:-America/Bogota}');" >> "$CONFIG_FILE"

  chown www-data:www-data "$CONFIG_FILE"
  chmod 644 "$CONFIG_FILE"
  echo "PHPNuxBill config.php creado ✓"
fi

# ── 3. Wait for MariaDB ──
echo "Esperando MariaDB..."
CONNECTED=false
for i in $(seq 1 30); do
  if php -r "new mysqli('${NUXBILL_DB_HOST:-mariadb}', '${NUXBILL_DB_USER:-nuxbill}', '${NUXBILL_DB_PASS:-changeme}', '${NUXBILL_DB_NAME:-phpnuxbill}');" 2>/dev/null; then
    echo "MariaDB conectada ✓"
    CONNECTED=true
    break
  fi
  echo "Reintentando ($i/30)..."
  sleep 2
done

# ── 4. Auto-install schema ──
SCHEMA_FOUND=false
if [ "$CONNECTED" = true ]; then
  TABLE_CHECK=$(php -r "
    \$c = new mysqli('${NUXBILL_DB_HOST:-mariadb}', '${NUXBILL_DB_USER:-nuxbill}', '${NUXBILL_DB_PASS:-changeme}', '${NUXBILL_DB_NAME:-phpnuxbill}');
    \$r = \$c->query(\"SHOW TABLES LIKE 'tbl_appconfig'\");
    echo ((\$r && \$r->num_rows > 0) ? '1' : '0');
    \$c->close();
  " 2>/dev/null || echo "0")

  if [ "$TABLE_CHECK" = "0" ]; then
    echo "Tablas no encontradas, buscando schema..."

    echo "Archivos SQL disponibles:"
    find "$NUXROOT" -name "*.sql" 2>/dev/null | head -20

    for sql_file in \
      "$NUXROOT/install/phpnuxbill.sql" \
      "$NUXROOT/install/sql/phpnuxbill.sql" \
      "$NUXROOT/system/uploads/phpnuxbill.sql" \
      "$NUXROOT/install/database.sql" \
      "$NUXROOT/install/install.sql" \
      "$NUXROOT/sql/install.sql" \
      $(find "$NUXROOT" -name "phpnuxbill.sql" 2>/dev/null) \
      $(find "$NUXROOT/install" -name "*.sql" 2>/dev/null | head -3); do
      [ -z "$sql_file" ] && continue
      if [ -f "$sql_file" ]; then
        echo "Importando schema: $sql_file"
        php -r "
          \$c = new mysqli('${NUXBILL_DB_HOST:-mariadb}', '${NUXBILL_DB_USER:-nuxbill}', '${NUXBILL_DB_PASS:-changeme}', '${NUXBILL_DB_NAME:-phpnuxbill}');
          \$sql = file_get_contents('$sql_file');
          \$c->multi_query(\$sql);
          while (\$c->next_result()) {;}
          \$c->close();
          echo 'OK';
        " 2>/dev/null && SCHEMA_FOUND=true
        if [ "$SCHEMA_FOUND" = true ]; then
          break
        fi
      fi
    done

    if [ "$SCHEMA_FOUND" = true ]; then
      echo "Schema importado ✓"
    else
      echo "⚠ No se encontró schema SQL. Acceda vía navegador para instalar."
      if [ -d "$NUXROOT/install" ]; then
        chown -R www-data:www-data "$NUXROOT/install"
        echo "Directorio install/ disponible para instalación web"
      fi
    fi
  else
    echo "PHPNuxBill schema ya existe ✓"
    SCHEMA_FOUND=true  
  fi
fi

# ── 5. Create admin user and set Live stage ──
if [ "$CONNECTED" = true ] && [ "$SCHEMA_FOUND" = true ]; then
  php -r "
    \$c = new mysqli('${NUXBILL_DB_HOST:-mariadb}', '${NUXBILL_DB_USER:-nuxbill}', '${NUXBILL_DB_PASS:-changeme}', '${NUXBILL_DB_NAME:-phpnuxbill}');
    if (\$c->connect_error) { echo 'DB error'; exit; }

    \$r = \$c->query(\"SELECT id FROM tbl_users WHERE username='admin'\");
    if (\$r && \$r->num_rows == 0) {
      \$hash = md5('admin');
      \$c->query(\"INSERT INTO tbl_users (username, password, fullname, user_type, status) VALUES ('admin', '\$hash', 'Administrator', 'Admin', 'Active')\");
      echo 'Admin creado (admin/admin) ✓';
    } else {
      echo 'Admin ya existe ✓';
    }

    // Force Live stage
    \$c->query(\"INSERT INTO tbl_appconfig (setting, value) VALUES ('app_stage', 'Live') ON DUPLICATE KEY UPDATE value='Live'\");

    \$c->close();
  " 2>/dev/null || true

  # Remove install directory to prevent redirect loop
  if [ -d "$NUXROOT/install" ]; then
    mv "$NUXROOT/install" "$NUXROOT/install.bak" 2>/dev/null || true
    echo "Directorio install/ renombrado a install.bak ✓"
  fi
fi

# ── 6. Permissions ──
chown -R www-data:www-data "$NUXROOT"
chmod -R 755 "$NUXROOT"

# ── 7. Setup cron via HTTP (PHPNuxBill requires full web context) ──
echo "Configurando cron job..."

# Register cron as active in NuxBill database
if [ "$CONNECTED" = true ] && [ "$SCHEMA_FOUND" = true ]; then
  php -r "
    \$c = new mysqli('${NUXBILL_DB_HOST:-mariadb}', '${NUXBILL_DB_USER:-nuxbill}', '${NUXBILL_DB_PASS:-changeme}', '${NUXBILL_DB_NAME:-phpnuxbill}');
    if (!\$c->connect_error) {
      \$settings = [
        'cron_last_run' => date('Y-m-d H:i:s'),
        'cron_period' => '1',
        'cron_status' => '1',
        'cron_active' => '1',
        'disable_cron_warning' => '1',
        'cron_enabled' => '1',
        'cron_enable' => '1',
        'cron_warning' => '0',
      ];

      foreach (\$settings as \$k => \$v) {
        \$ks = \$c->real_escape_string(\$k);
        \$vs = \$c->real_escape_string(\$v);
        \$c->query(\"DELETE FROM tbl_appconfig WHERE setting='\$ks'\");
        \$c->query(\"INSERT INTO tbl_appconfig (setting, value) VALUES ('\$ks', '\$vs')\");
      }

      \$c->close();
      echo 'Cron registrado en DB ✓';
    }
  " 2>/dev/null || true
fi

# Write cron entry that calls NuxBill via HTTP (full web context)
# PHPNuxBill cron routes: /?_route=cron/run  OR  /index.php?_route=cron/run
CRON_URL="http://127.0.0.1:8080/index.php?_route=cron/run"

echo "* * * * * root curl -sf '${CRON_URL}' > /dev/null 2>&1" > /etc/cron.d/phpnuxbill
chmod 0644 /etc/cron.d/phpnuxbill
echo "Cron job HTTP configurado: ${CRON_URL} ✓"

# Start cron daemon
if command -v cron &>/dev/null; then
  cron && echo "Cron daemon iniciado ✓"
elif command -v crond &>/dev/null; then
  crond && echo "Cron daemon iniciado ✓"
fi

# Background loop: call cron via HTTP every 5 min + keep heartbeat fresh
(
  # Wait for Apache to be ready
  sleep 15
  echo "[cron-loop] Primera ejecución..."
  while true; do
    # Call the actual cron route via HTTP (this executes billing, expiry, etc.)
    HTTP_CODE=$(curl -sf -o /dev/null -w '%{http_code}' "${CRON_URL}" 2>/dev/null || echo "000")

    # Update heartbeat timestamp so NuxBill UI never shows warning
    php -r "
      \$c = @new mysqli('${NUXBILL_DB_HOST:-mariadb}', '${NUXBILL_DB_USER:-nuxbill}', '${NUXBILL_DB_PASS:-changeme}', '${NUXBILL_DB_NAME:-phpnuxbill}');
      if (!\$c->connect_error) {
        \$c->query(\"UPDATE tbl_appconfig SET value=NOW() WHERE setting='cron_last_run'\");
        \$c->query(\"UPDATE tbl_appconfig SET value='1' WHERE setting IN ('cron_active','cron_status','cron_enabled','cron_enable','disable_cron_warning')\");
        \$c->query(\"UPDATE tbl_appconfig SET value='0' WHERE setting='cron_warning'\");
        \$c->close();
      }
    " >/dev/null 2>&1 || true

    sleep 300  # every 5 minutes
  done
) &
echo "Cron HTTP loop (5min) iniciado ✓"

# Patch warning text in templates (cosmetic)
WARN_FILES=$(grep -Ril "Cron appear not been setup" "$NUXROOT" 2>/dev/null || true)
if [ -n "$WARN_FILES" ]; then
  echo "$WARN_FILES" | while IFS= read -r f; do
    [ -n "$f" ] && sed -i "s/Cron appear not been setup, please check your cron setup\./Cron scheduler is active./g" "$f" || true
  done
  echo "Patch de mensaje cron aplicado ✓"
fi

echo "Cron configurado ✓"
echo "=== PHPNuxBill listo ==="
exec "$@"
