#!/bin/bash
set -e

echo "=== Configurando daloRADIUS ==="

# ── 1. Locate the actual web root (varies by daloRADIUS version) ──
WEBROOT="/var/www/html"

# Newer daloRADIUS (2.x) puts everything under app/
if [ -d "$WEBROOT/app" ]; then
  LAYOUT="v2"
  echo "Detectado daloRADIUS v2 layout (app/)"
else
  LAYOUT="v1"
  echo "Detectado daloRADIUS v1 layout (library/)"
fi

# ── 2. Create / overwrite the config file in the RIGHT location ──
if [ "$LAYOUT" = "v2" ]; then
  CONFIG_DIR="$WEBROOT/app/common/includes"
  CONFIG_FILE="$CONFIG_DIR/daloradius.conf.php"
else
  CONFIG_DIR="$WEBROOT/library"
  CONFIG_FILE="$CONFIG_DIR/daloradius.conf.php"
fi

mkdir -p "$CONFIG_DIR"

cat > "$CONFIG_FILE" << 'PHPEOF'
<?php
// Auto-generated by OmniSync installer
$configValues = array();

$configValues['FREERADIUS_VERSION']  = '3';
$configValues['CONFIG_DB_ENGINE']    = 'mysqli';
PHPEOF

# Append dynamic values (can't use heredoc with both PHP $ and shell $)
cat >> "$CONFIG_FILE" << DYNEOF
\$configValues['CONFIG_DB_HOST'] = '${MYSQL_HOST:-mariadb}';
\$configValues['CONFIG_DB_PORT'] = '${MYSQL_PORT:-3306}';
\$configValues['CONFIG_DB_USER'] = '${MYSQL_USER:-radius}';
\$configValues['CONFIG_DB_PASS'] = '${MYSQL_PASSWORD:-radiusdbpw}';
\$configValues['CONFIG_DB_NAME'] = '${MYSQL_DATABASE:-radius}';

\$configValues['CONFIG_DB_TBL_RADCHECK']       = 'radcheck';
\$configValues['CONFIG_DB_TBL_RADREPLY']        = 'radreply';
\$configValues['CONFIG_DB_TBL_RADGROUPCHECK']   = 'radgroupcheck';
\$configValues['CONFIG_DB_TBL_RADGROUPREPLY']   = 'radgroupreply';
\$configValues['CONFIG_DB_TBL_RADUSERGROUP']    = 'radusergroup';
\$configValues['CONFIG_DB_TBL_RADACCT']         = 'radacct';
\$configValues['CONFIG_DB_TBL_RADPOSTAUTH']     = 'radpostauth';
\$configValues['CONFIG_DB_TBL_RADNAS']          = 'nas';
\$configValues['CONFIG_DB_TBL_DALOOPERATOR']    = 'operators';
\$configValues['CONFIG_DB_TBL_DALORATES']       = 'rates';
\$configValues['CONFIG_DB_TBL_DALOHOTSPOTS']    = 'hotspots';
\$configValues['CONFIG_DB_TBL_DALOUSERINFO']    = 'userinfo';
\$configValues['CONFIG_DB_TBL_DALOUSERBILLINFO']= 'userbillinfo';
\$configValues['CONFIG_DB_TBL_DALOBILLINGPLANS']= 'billing_plans';
\$configValues['CONFIG_DB_TBL_DALOBILLINGHISTORY']= 'billing_history';
\$configValues['CONFIG_DB_TBL_DALOBILLINGPAYPAL']= 'billing_paypal';
\$configValues['CONFIG_DB_TBL_DALODICTIONARY']  = 'dictionary';
\$configValues['CONFIG_DB_TBL_DALOBILLINGMERCHANT']= 'billing_merchant';
\$configValues['CONFIG_DB_TBL_DALOBATCHHISTORY']= 'batch_history';
\$configValues['CONFIG_DB_TBL_DALOPROXYS']      = 'proxys';
\$configValues['CONFIG_DB_TBL_DALONODE']        = 'node';

\$configValues['CONFIG_PATH_DALO_VARIABLE_DATA'] = '/var/www/html/var';
\$configValues['CONFIG_PATH_FRAMEWORK_DIRECTORY'] = '/var/www/html/app/common/library';

\$configValues['CONFIG_LOG_FILE']  = '/tmp/daloradius.log';
\$configValues['CONFIG_LOG_PAGES'] = 'no';
\$configValues['CONFIG_IFACE_PASSWORD_HIDDEN'] = 'no';
\$configValues['CONFIG_LANG']      = 'en';
\$configValues['CONFIG_MAIL_SMTPADDR']  = '127.0.0.1';
\$configValues['CONFIG_MAIL_PORT']      = '25';
\$configValues['CONFIG_MAIL_FROM']      = 'root@localhost';
\$configValues['CONFIG_MAIL_FROMNAME']  = 'daloRADIUS Mailer';
DYNEOF

chown www-data:www-data "$CONFIG_FILE"
echo "daloRADIUS config creado: $CONFIG_FILE ✓"

# ── 3. Create var directory for daloRADIUS data ──
mkdir -p "$WEBROOT/var"
chown -R www-data:www-data "$WEBROOT/var"

# ── 4. Wait for MariaDB ──
echo "Esperando MariaDB..."
for i in $(seq 1 30); do
  if php -r "new mysqli('${MYSQL_HOST:-mariadb}', '${MYSQL_USER:-radius}', '${MYSQL_PASSWORD:-radiusdbpw}', '${MYSQL_DATABASE:-radius}');" 2>/dev/null; then
    echo "MariaDB conectada ✓"

    # Check if radcheck table exists
    TABLE_EXISTS=$(php -r "
      \$c = new mysqli('${MYSQL_HOST:-mariadb}', '${MYSQL_USER:-radius}', '${MYSQL_PASSWORD:-radiusdbpw}', '${MYSQL_DATABASE:-radius}');
      \$r = \$c->query(\"SHOW TABLES LIKE 'radcheck'\");
      echo (\$r && \$r->num_rows > 0) ? '1' : '0';
      \$c->close();
    " 2>/dev/null || echo "0")

    if [ "$TABLE_EXISTS" = "0" ]; then
      echo "Importando esquema RADIUS..."
      for sql_file in \
        "$WEBROOT/contrib/db/fr3-mariadb-freeradius.sql" \
        "$WEBROOT/contrib/db/mariadb-freeradius.sql" \
        "$WEBROOT/contrib/db/mysql-freeradius.sql"; do
        if [ -f "$sql_file" ]; then
          echo "Importando: $sql_file"
          php -r "
            \$c = new mysqli('${MYSQL_HOST:-mariadb}', '${MYSQL_USER:-radius}', '${MYSQL_PASSWORD:-radiusdbpw}', '${MYSQL_DATABASE:-radius}');
            \$sql = file_get_contents('$sql_file');
            \$c->multi_query(\$sql);
            while (\$c->next_result()) {;}
            \$c->close();
          " 2>/dev/null || true
          break
        fi
      done

      # Import daloRADIUS schema
      for sql_file in \
        "$WEBROOT/contrib/db/mariadb-daloradius.sql" \
        "$WEBROOT/contrib/db/mysql-daloradius.sql"; do
        if [ -f "$sql_file" ]; then
          echo "Importando: $sql_file"
          php -r "
            \$c = new mysqli('${MYSQL_HOST:-mariadb}', '${MYSQL_USER:-radius}', '${MYSQL_PASSWORD:-radiusdbpw}', '${MYSQL_DATABASE:-radius}');
            \$sql = file_get_contents('$sql_file');
            \$c->multi_query(\$sql);
            while (\$c->next_result()) {;}
            \$c->close();
          " 2>/dev/null || true
          break
        fi
      done
      echo "Esquema RADIUS importado ✓"
    else
      echo "Esquema RADIUS ya existe ✓"
    fi
    break
  fi
  echo "Reintentando ($i/30)..."
  sleep 2
done

exec "$@"
