#!/bin/bash
set -e

echo "=== Configurando daloRADIUS ==="

WEBROOT="/var/www/html"

# ── 1. Detect layout version ──
if [ -d "$WEBROOT/app" ]; then
  LAYOUT="v2"
  CONFIG_DIR="$WEBROOT/app/common/includes"
  echo "Detectado daloRADIUS v2 layout"
else
  LAYOUT="v1"
  CONFIG_DIR="$WEBROOT/library"
  echo "Detectado daloRADIUS v1 layout"
fi

# ── 2. Create config file ──
CONFIG_FILE="$CONFIG_DIR/daloradius.conf.php"
mkdir -p "$CONFIG_DIR"

echo "Creando config en: $CONFIG_FILE"

# Write config using echo to avoid heredoc escaping issues
echo '<?php' > "$CONFIG_FILE"
echo '// Auto-generated by OmniSync installer' >> "$CONFIG_FILE"
echo '$configValues = array();' >> "$CONFIG_FILE"
echo '' >> "$CONFIG_FILE"
echo "\$configValues['FREERADIUS_VERSION']  = '3';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_ENGINE']    = 'mysqli';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_HOST']      = '${MYSQL_HOST:-mariadb}';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_PORT']      = '${MYSQL_PORT:-3306}';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_USER']      = '${MYSQL_USER:-radius}';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_PASS']      = '${MYSQL_PASSWORD:-radiusdbpw}';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_NAME']      = '${MYSQL_DATABASE:-radius}';" >> "$CONFIG_FILE"
echo '' >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_RADCHECK']       = 'radcheck';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_RADREPLY']        = 'radreply';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_RADGROUPCHECK']   = 'radgroupcheck';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_RADGROUPREPLY']   = 'radgroupreply';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_RADUSERGROUP']    = 'radusergroup';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_RADACCT']         = 'radacct';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_RADPOSTAUTH']     = 'radpostauth';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_RADNAS']          = 'nas';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_DALOOPERATOR']    = 'operators';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_DALORATES']       = 'rates';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_DALOHOTSPOTS']    = 'hotspots';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_DALOUSERINFO']    = 'userinfo';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_DALOUSERBILLINFO']= 'userbillinfo';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_DALOBILLINGPLANS']= 'billing_plans';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_DALOBILLINGHISTORY']= 'billing_history';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_DALOBILLINGPAYPAL']= 'billing_paypal';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_DALODICTIONARY']  = 'dictionary';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_DALOBILLINGMERCHANT']= 'billing_merchant';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_DALOBATCHHISTORY']= 'batch_history';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_DALOPROXYS']      = 'proxys';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_DALONODE']        = 'node';" >> "$CONFIG_FILE"
echo '' >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_PATH_DALO_VARIABLE_DATA'] = '/var/www/html/var';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_PATH_FRAMEWORK_DIRECTORY'] = '/var/www/html/app/common/library';" >> "$CONFIG_FILE"
echo '' >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_LOG_FILE']  = '/tmp/daloradius.log';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_LOG_PAGES'] = 'no';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_IFACE_PASSWORD_HIDDEN'] = 'no';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_LANG']      = 'en';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_MAIL_SMTPADDR']  = '127.0.0.1';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_MAIL_PORT']      = '25';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_MAIL_FROM']      = 'root@localhost';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_MAIL_FROMNAME']  = 'daloRADIUS Mailer';" >> "$CONFIG_FILE"

chown www-data:www-data "$CONFIG_FILE"
chmod 644 "$CONFIG_FILE"
echo "Config creado ✓ — verificando:"
ls -la "$CONFIG_FILE"
head -5 "$CONFIG_FILE"

# ── 3. Create var directory ──
mkdir -p "$WEBROOT/var"
chown -R www-data:www-data "$WEBROOT/var"

# ── 4. Wait for MariaDB ──
echo "Esperando MariaDB..."
for i in $(seq 1 30); do
  if php -r "new mysqli('${MYSQL_HOST:-mariadb}', '${MYSQL_USER:-radius}', '${MYSQL_PASSWORD:-radiusdbpw}', '${MYSQL_DATABASE:-radius}');" 2>/dev/null; then
    echo "MariaDB conectada ✓"

    TABLE_EXISTS=$(php -r "
      \$c = new mysqli('${MYSQL_HOST:-mariadb}', '${MYSQL_USER:-radius}', '${MYSQL_PASSWORD:-radiusdbpw}', '${MYSQL_DATABASE:-radius}');
      \$r = \$c->query(\"SHOW TABLES LIKE 'radcheck'\");
      echo (\$r && \$r->num_rows > 0) ? '1' : '0';
      \$c->close();
    " 2>/dev/null || echo "0")

    if [ "$TABLE_EXISTS" = "0" ]; then
      echo "Importando esquema RADIUS..."
      for sql_file in \
        "$WEBROOT/contrib/db/fr3-mariadb-freeradius.sql" \
        "$WEBROOT/contrib/db/mariadb-freeradius.sql" \
        "$WEBROOT/contrib/db/mysql-freeradius.sql"; do
        if [ -f "$sql_file" ]; then
          echo "Importando: $sql_file"
          php -r "
            \$c = new mysqli('${MYSQL_HOST:-mariadb}', '${MYSQL_USER:-radius}', '${MYSQL_PASSWORD:-radiusdbpw}', '${MYSQL_DATABASE:-radius}');
            \$sql = file_get_contents('$sql_file');
            \$c->multi_query(\$sql);
            while (\$c->next_result()) {;}
            \$c->close();
          " 2>/dev/null || true
          break
        fi
      done

      for sql_file in \
        "$WEBROOT/contrib/db/mariadb-daloradius.sql" \
        "$WEBROOT/contrib/db/mysql-daloradius.sql"; do
        if [ -f "$sql_file" ]; then
          echo "Importando daloRADIUS schema: $sql_file"
          php -r "
            \$c = new mysqli('${MYSQL_HOST:-mariadb}', '${MYSQL_USER:-radius}', '${MYSQL_PASSWORD:-radiusdbpw}', '${MYSQL_DATABASE:-radius}');
            \$sql = file_get_contents('$sql_file');
            \$c->multi_query(\$sql);
            while (\$c->next_result()) {;}
            \$c->close();
          " 2>/dev/null || true
          break
        fi
      done
      echo "Esquema RADIUS importado ✓"
    else
      echo "Esquema RADIUS ya existe ✓"
    fi
    break
  fi
  echo "Reintentando ($i/30)..."
  sleep 2
done

exec "$@"
