#!/bin/bash
set -e

echo "=== Configurando daloRADIUS ==="

WEBROOT="/var/www/html"

# ── 1. Detect layout version ──
if [ -d "$WEBROOT/app" ]; then
  LAYOUT="v2"
  CONFIG_DIR="$WEBROOT/app/common/includes"
  echo "Detectado daloRADIUS v2 layout"
else
  LAYOUT="v1"
  CONFIG_DIR="$WEBROOT/library"
  echo "Detectado daloRADIUS v1 layout"
fi

# ── 2. Create config file ──
CONFIG_FILE="$CONFIG_DIR/daloradius.conf.php"
mkdir -p "$CONFIG_DIR"

echo "Creando config en: $CONFIG_FILE"

echo '<?php' > "$CONFIG_FILE"
echo '// Auto-generated by OmniSync installer' >> "$CONFIG_FILE"
echo '$configValues = array();' >> "$CONFIG_FILE"
echo '' >> "$CONFIG_FILE"
echo "\$configValues['FREERADIUS_VERSION']  = '3';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_ENGINE']    = 'mysqli';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_HOST']      = '${MYSQL_HOST:-mariadb}';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_PORT']      = '${MYSQL_PORT:-3306}';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_USER']      = '${MYSQL_USER:-radius}';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_PASS']      = '${MYSQL_PASSWORD:-radiusdbpw}';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_NAME']      = '${MYSQL_DATABASE:-radius}';" >> "$CONFIG_FILE"
echo '' >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_RADCHECK']       = 'radcheck';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_RADREPLY']        = 'radreply';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_RADGROUPCHECK']   = 'radgroupcheck';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_RADGROUPREPLY']   = 'radgroupreply';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_RADUSERGROUP']    = 'radusergroup';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_RADACCT']         = 'radacct';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_RADPOSTAUTH']     = 'radpostauth';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_RADNAS']          = 'nas';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_DALOOPERATORS']    = 'operators';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_DALOOPERATOR']     = 'operators';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_DALOOPERATORS_ACL'] = 'operators_acl';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_DALOOPERATORS_ACL_FILES'] = 'operators_acl_files';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_DALORATES']        = 'rates';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_DALOHOTSPOTS']     = 'hotspots';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_DALOUSERINFO']     = 'userinfo';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_DALOUSERBILLINFO'] = 'userbillinfo';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_DALOBILLINGPLANS'] = 'billing_plans';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_DALOBILLINGRATES'] = 'billing_rates';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_DALOBILLINGHISTORY'] = 'billing_history';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_DALOBILLINGPAYPAL'] = 'billing_paypal';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_DALODICTIONARY']  = 'dictionary';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_DALOREALMS']      = 'realms';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_DALOBILLINGMERCHANT'] = 'billing_merchant';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_DALOBATCHHISTORY'] = 'batch_history';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_DALOPROXYS']       = 'proxys';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_DALONODE']         = 'node';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_DB_TBL_DALOMESSAGES']     = 'messages';" >> "$CONFIG_FILE"
echo '' >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_PATH_DALO_VARIABLE_DATA'] = '/var/www/html/var';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_PATH_FRAMEWORK_DIRECTORY'] = '/var/www/html/app/common/library';" >> "$CONFIG_FILE"
echo '' >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_LOG_FILE']  = '/tmp/daloradius.log';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_LOG_PAGES'] = 'no';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_IFACE_PASSWORD_HIDDEN'] = 'no';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_LANG']      = 'en';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_MAIL_SMTPADDR']  = '127.0.0.1';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_MAIL_PORT']      = '25';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_MAIL_FROM']      = 'root@localhost';" >> "$CONFIG_FILE"
echo "\$configValues['CONFIG_MAIL_FROMNAME']  = 'daloRADIUS Mailer';" >> "$CONFIG_FILE"

chown www-data:www-data "$CONFIG_FILE"
chmod 644 "$CONFIG_FILE"
echo "Config creado ✓"

# ── 3. Create var directory ──
mkdir -p "$WEBROOT/var"
chown -R www-data:www-data "$WEBROOT/var"

# ── 4. Wait for MariaDB and import ALL schemas ──
echo "Esperando MariaDB..."
for i in $(seq 1 30); do
  if php -r "new mysqli('${MYSQL_HOST:-mariadb}', '${MYSQL_USER:-radius}', '${MYSQL_PASSWORD:-radiusdbpw}', '${MYSQL_DATABASE:-radius}');" 2>/dev/null; then
    echo "MariaDB conectada ✓"

    # Always import our full schema (uses IF NOT EXISTS so it's safe to re-run)
    SCHEMA_FILE="/docker-entrypoint-initdb.d/radius-schema.sql"
    if [ -f "$SCHEMA_FILE" ]; then
      echo "Importando schema completo desde $SCHEMA_FILE..."
      php -r "
        \$c = new mysqli('${MYSQL_HOST:-mariadb}', '${MYSQL_USER:-radius}', '${MYSQL_PASSWORD:-radiusdbpw}', '${MYSQL_DATABASE:-radius}');
        \$sql = file_get_contents('$SCHEMA_FILE');
        \$c->multi_query(\$sql);
        while (\$c->next_result()) {;}
        \$c->close();
        echo 'OK';
      " 2>/dev/null || true
      echo "Schema importado ✓"
    fi

    # Also try daloRADIUS bundled schemas as fallback
    TABLE_EXISTS=$(php -r "
      \$c = new mysqli('${MYSQL_HOST:-mariadb}', '${MYSQL_USER:-radius}', '${MYSQL_PASSWORD:-radiusdbpw}', '${MYSQL_DATABASE:-radius}');
      \$r = \$c->query(\"SHOW TABLES LIKE 'radcheck'\");
      echo (\$r && \$r->num_rows > 0) ? '1' : '0';
      \$c->close();
    " 2>/dev/null || echo "0")

    if [ "$TABLE_EXISTS" = "0" ]; then
      echo "Tablas RADIUS no encontradas, importando desde daloRADIUS..."
      for sql_file in \
        "$WEBROOT/contrib/db/fr3-mariadb-freeradius.sql" \
        "$WEBROOT/contrib/db/mariadb-freeradius.sql" \
        "$WEBROOT/contrib/db/mysql-freeradius.sql"; do
        if [ -f "$sql_file" ]; then
          echo "Importando: $sql_file"
          php -r "
            \$c = new mysqli('${MYSQL_HOST:-mariadb}', '${MYSQL_USER:-radius}', '${MYSQL_PASSWORD:-radiusdbpw}', '${MYSQL_DATABASE:-radius}');
            \$sql = file_get_contents('$sql_file');
            \$c->multi_query(\$sql);
            while (\$c->next_result()) {;}
            \$c->close();
          " 2>/dev/null || true
          break
        fi
      done

      for sql_file in \
        "$WEBROOT/contrib/db/mariadb-daloradius.sql" \
        "$WEBROOT/contrib/db/mysql-daloradius.sql"; do
        if [ -f "$sql_file" ]; then
          echo "Importando daloRADIUS schema: $sql_file"
          php -r "
            \$c = new mysqli('${MYSQL_HOST:-mariadb}', '${MYSQL_USER:-radius}', '${MYSQL_PASSWORD:-radiusdbpw}', '${MYSQL_DATABASE:-radius}');
            \$sql = file_get_contents('$sql_file');
            \$c->multi_query(\$sql);
            while (\$c->next_result()) {;}
            \$c->close();
          " 2>/dev/null || true
          break
        fi
      done
    fi

    # Verify critical tables exist, create if missing
    echo "Verificando tablas críticas..."
    php -r "
      \$c = new mysqli('${MYSQL_HOST:-mariadb}', '${MYSQL_USER:-radius}', '${MYSQL_PASSWORD:-radiusdbpw}', '${MYSQL_DATABASE:-radius}');
      if (\$c->connect_error) { echo 'DB error'; exit; }

      // Check and create messages table if missing
      \$r = \$c->query(\"SHOW TABLES LIKE 'messages'\");
      if (\$r && \$r->num_rows == 0) {
        \$c->query(\"CREATE TABLE messages (
          id int(11) NOT NULL auto_increment,
          type varchar(32) NOT NULL default '',
          content text,
          modified_on datetime default NULL,
          modified_by varchar(128) default NULL,
          created_on datetime default NULL,
          created_by varchar(128) default NULL,
          PRIMARY KEY (id)
        )\");
        \$c->query(\"INSERT INTO messages (type, content, created_on, created_by) VALUES ('login', 'Welcome to daloRADIUS - OmniSync ISP Manager', NOW(), 'system')\");
        echo 'Tabla messages creada ✓ ';
      }

      // Check and create operators table if missing
      \$r = \$c->query(\"SHOW TABLES LIKE 'operators'\");
      if (\$r && \$r->num_rows == 0) {
        \$c->query(\"CREATE TABLE operators (
          id int(11) NOT NULL auto_increment,
          username varchar(32) NOT NULL default '',
          password varchar(32) NOT NULL default '',
          firstname varchar(32) default NULL,
          lastname varchar(32) default NULL,
          title varchar(32) default NULL,
          department varchar(32) default NULL,
          company varchar(32) default NULL,
          phone1 varchar(32) default NULL,
          phone2 varchar(32) default NULL,
          email1 varchar(64) default NULL,
          email2 varchar(64) default NULL,
          messenger1 varchar(64) default NULL,
          messenger2 varchar(64) default NULL,
          notes varchar(128) default NULL,
          lastlogin datetime default NULL,
          privilege varchar(64) default NULL,
          PRIMARY KEY (id)
        )\");
        \$c->query(\"INSERT INTO operators (username, password, firstname, privilege) VALUES ('administrator', 'radius', 'Administrator', 'full')\");
        echo 'Tabla operators creada ✓ ';
      }

      \$c->close();
    " 2>/dev/null || true

    echo "Verificación de tablas completa ✓"
    break
  fi
  echo "Reintentando ($i/30)..."
  sleep 2
done

exec "$@"
